In [5]:
import numpy as np

In [4]:
n1 = np.array([1,2,3,4,5,6])
n1

array([1, 2, 3, 4, 5, 6])

In [7]:
n2 = np.array([[1,2,3,4,5,6],[10,20,30,40,50,60]])
n2

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [8]:
type(n2)

numpy.ndarray

In [9]:
type(n1)

numpy.ndarray

In [10]:
n3 = np.zeros((1,2))

In [11]:
n3

array([[0., 0.]])

In [12]:
n4 = np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
n5 = np.full((2,2),10)
n5

array([[10, 10],
       [10, 10]])

In [14]:
n6 = np.full((3,6),9)
n6

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [15]:
n7 = np.arange(10,20)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
n8 = np.arange(10,50,5)
n8

array([10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
n9 = np.random.randint(1,100,5)
n9

array([66, 75, 32, 40,  4])

In [18]:
n10 = np.array([[1,2,3],[4,5,6]])
n10

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
n10.shape

(2, 3)

In [21]:
n10.shape = (3,2)
n10

array([[1, 2],
       [3, 4],
       [5, 6]])