In [12]:
import numpy as np
import pandas as pd
import os

In [3]:
n1 = np.array([10,20,30])
#n2 = np.array([40,50,60,])
print(n1)
n2

[10 20 30]


array([40, 50, 60])

In [6]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [8]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [14]:
n2 = np.array([10,20,30,40,50,60])
n3 = np.array([50,60,70,80,90])
np.intersect1d(n1,n2)

array([10, 20, 30])

In [15]:
np.setdiff1d(n2,n3)

array([10, 20, 30, 40])

In [16]:
np.intersect1d(n2,n3)

array([50, 60])

In [17]:
np.setdiff1d(n2,n3)

array([10, 20, 30, 40])

In [18]:
np.setdiff1d(n3,n2)

array([70, 80, 90])

In [21]:
n4 = np.array([10,20])
n5 = np.array([30,40])
np.sum([n4,n5])

100

In [22]:
np.sum([n4,n5],axis=0)

array([40, 60])

In [23]:
np.sum([n4,n5],axis=1)

array([30, 70])

In [24]:
n4 = n4+1
n4

array([11, 21])

In [25]:
n5 = n5*2
n5

array([60, 80])

In [26]:
n4 = n4-3
n4

array([ 8, 18])

In [28]:
n5 =n5/2
n5

array([30., 40.])

In [29]:
n6 = np.array([10,20,30,40,50,60,70])
np.mean(n6)

40.0

In [30]:
np.median(n6)

40.0

In [31]:
np.std(n6)

20.0

In [33]:
n7 = np.array([1,2,3,4,5,6,7,8,9])
np.save("mynumpy",n7)

In [34]:
n8 = np.load("mynumpy.npy")
n8

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
#import pandas as pd
s1=pd.Series([1,2,3,4,5,6])
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [38]:
type(s1)

pandas.core.series.Series

In [40]:
s2 = pd.Series([5,6,7,8,9], index=['a','b','c','d','e'])
s2

a    5
b    6
c    7
d    8
e    9
dtype: int64

In [42]:
s3 = pd.Series({'a':100,'b':200,'c':300,'d':400},index={'a','b','c','d','e'})
s3

b    200.0
e      NaN
d    400.0
c    300.0
a    100.0
dtype: float64

In [44]:
s4 = pd.Series([1,2,3,4,5,6,7,8,9])
s4[4]

5

In [46]:
s4[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [47]:
s4[-3:]

6    7
7    8
8    9
dtype: int64

In [48]:
s4[3:6]

3    4
4    5
5    6
dtype: int64

In [50]:
s4+2
s4

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [51]:
s5 = pd.Series([1,2,3,4])
s5+3

0    4
1    5
2    6
3    7
dtype: int64

In [52]:
s6 = pd.Series([2,4,6,8,10])
s7 = pd.Series([1,3,5,7,9])
s6+s7

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [55]:
df1 = pd.DataFrame({"Name":['Bob','Sam','Anne'],"Marks":[76,25,92]})

In [56]:
df1

Name  Marks
0   Bob     76
1   Sam     25
2  Anne     92

In [5]:
#iris_data=pd.read_csv("iris.csv")

In [15]:
iris_data = pd.read_csv("C:\\Users\\Tawanda\\Downloads\\iris.csv")

In [7]:
iris_data

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [16]:
iris_data.tail

<bound method NDFrame.tail of      Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [10]:
iris_data.shape

(150, 5)

In [17]:
iris_data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
iris_data.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [19]:
iris_data.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [21]:
iris_data.iloc[0:5,0:3]

Sepal.Length  Sepal.Width  Petal.Length
0           5.1          3.5           1.4
1           4.9          3.0           1.4
2           4.7          3.2           1.3
3           4.6          3.1           1.5
4           5.0          3.6           1.4

In [24]:
iris_data.loc[0:4,("Sepal.Length","Petal.Length")]

Sepal.Length  Petal.Length
0           5.1           1.4
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5
4           5.0           1.4

In [25]:
iris_data.loc[9:15,("Sepal.Length","Petal.Width")]

Sepal.Length  Petal.Width
9            4.9          0.1
10           5.4          0.2
11           4.8          0.2
12           4.8          0.1
13           4.3          0.1
14           5.8          0.2
15           5.7          0.4

In [26]:
iris_data.drop("Sepal.Length",axis=1)

Sepal.Width  Petal.Length  Petal.Width    Species
0            3.5           1.4          0.2     setosa
1            3.0           1.4          0.2     setosa
2            3.2           1.3          0.2     setosa
3            3.1           1.5          0.2     setosa
4            3.6           1.4          0.2     setosa
..           ...           ...          ...        ...
145          3.0           5.2          2.3  virginica
146          2.5           5.0          1.9  virginica
147          3.0           5.2          2.0  virginica
148          3.4           5.4          2.3  virginica
149          3.0           5.1          1.8  virginica

[150 rows x 4 columns]

In [27]:
iris_data.drop([1,2,3],axis=0)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[147 rows x 5 columns]

In [28]:
iris_data.mean()

Sepal.Length    5.843333
Sepal.Width     3.057333
Petal.Length    3.758000
Petal.Width     1.199333
dtype: float64

In [29]:
iris_data.median(
)

Sepal.Length    5.80
Sepal.Width     3.00
Petal.Length    4.35
Petal.Width     1.30
dtype: float64

In [30]:
iris_data.max()

Sepal.Length          7.9
Sepal.Width           4.4
Petal.Length          6.9
Petal.Width           2.5
Species         virginica
dtype: object

In [31]:
iris_data.min()

Sepal.Length       4.3
Sepal.Width          2
Petal.Length         1
Petal.Width        0.1
Species         setosa
dtype: object

In [32]:
def half(s):
    return s*0.5

In [36]:
iris_data[['Sepal.Length','Sepal.Width']].apply(half)

Sepal.Length  Sepal.Width
0            2.55         1.75
1            2.45         1.50
2            2.35         1.60
3            2.30         1.55
4            2.50         1.80
..            ...          ...
145          3.35         1.50
146          3.15         1.25
147          3.25         1.50
148          3.10         1.70
149          2.95         1.50

[150 rows x 2 columns]

In [37]:
iris_data['Species'].value_counts()

versicolor    50
setosa        50
virginica     50
Name: Species, dtype: int64

In [38]:
iris_data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [39]:
iris_data.sort_values(by='Sepal.Length')

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]